import Person from '../Person';
import KnownFor from '../KnownFor';
import KnownForCard from '../KnownForCard';
export default [
  {
    component: Person,
    name: 'Person profile',
    props: {
      person: {
        birthday: '1968-10-11',
        known_for_department: 'Acting',
        deathday: null,
        id: 13636,
        name: 'Jane Krakowski',
        also_known_as: {},
        gender: 1,
        biography:
          "Jane Krakowski (born October 11, 1968) is an American actress and singer. She is known for playing Elaine Vassal on Ally McBeal and Jenna Maroney on 30 Rock, winning Screen Actors Guild Awards for both roles. She also regularly performs on the stage, winning a Tony Award for her performance in Nine, and an Olivier Award for Guys and Dolls in London's West End.\n\nDescription above from the Wikipedia article Jane Krakowski, licensed under CC-BY-SA, full list of contributors on Wikipedia .",
        popularity: 2.205,
        place_of_birth: 'Parsippany, New Jersey, USA',
        profile_path: '/l1ItJIV6PkWszahE9cv3ucsnmea.jpg',
        adult: false,
        imdb_id: 'nm0005105',
        homepage: null,
      },
    },
  },
  {
    component: KnownForCard,
    name: 'KnownFor card',
    props: {
      credit: {
        id: 425,
        character: 'Rachel (voice)',
        original_title: 'Ice Age',
        overview:
          'With the impending ice age almost upon them, a mismatched trio of prehistoric critters – Manny the woolly mammoth, Diego the saber-toothed tiger and Sid the giant sloth – find an orphaned infant and decide to return it to its human parents. Along the way, the unlikely allies become friends but, when enemies attack, their quest takes on far nobler aims.',
        vote_count: 6969,
        video: false,
        media_type: 'movie',
        release_date: '2002-03-15',
        vote_average: 7.2,
        title: 'Ice Age',
        popularity: 19.461,
        original_language: 'en',
        genre_ids: [16, 35, 10751, 12],
        backdrop_path: '/oDqbewoFuIEWA7UWurole6MzDGn.jpg',
        adult: false,
        poster_path: '/zpaQwR0YViPd83bx1e559QyZ35i.jpg',
        credit_id: '52fe4242c3a36847f8010397',
      },
    },
  },
  {
    component: KnownFor,
    name: 'KnownFor block',
    props: {
      credits: {
        cast: [
          {
            id: 425,
            character: 'Rachel (voice)',
            original_title: 'Ice Age',
            overview:
              'With the impending ice age almost upon them, a mismatched trio of prehistoric critters – Manny the woolly mammoth, Diego the saber-toothed tiger and Sid the giant sloth – find an orphaned infant and decide to return it to its human parents. Along the way, the unlikely allies become friends but, when enemies attack, their quest takes on far nobler aims.',
            vote_count: 6969,
            video: false,
            media_type: 'movie',
            release_date: '2002-03-15',
            vote_average: 7.2,
            title: 'Ice Age',
            popularity: 19.461,
            original_language: 'en',
            genre_ids: [16, 35, 10751, 12],
            backdrop_path: '/oDqbewoFuIEWA7UWurole6MzDGn.jpg',
            adult: false,
            poster_path: '/zpaQwR0YViPd83bx1e559QyZ35i.jpg',
            credit_id: '52fe4242c3a36847f8010397',
          },
          {
            id: 889,
            character: "Betty O'Shale",
            original_title: 'The Flintstones in Viva Rock Vegas',
            overview:
              "The Flintstones are at it again. The Flintstones and the Rubbles head for Rock Vegas with Fred hoping to court the lovely Wilma. Nothing will stand in the way of love, except for the conniving Chip Rockefeller who is the playboy born in Baysville but who has made it in the cutthroat town of Rock Vegas. Will Fred win Wilma's love?",
            vote_count: 295,
            video: false,
            media_type: 'movie',
            release_date: '2000-04-28',
            vote_average: 4.5,
            title: 'The Flintstones in Viva Rock Vegas',
            popularity: 8.056,
            original_language: 'en',
            genre_ids: [35, 878, 10749, 10751],
            backdrop_path: '/fqlDRnXRfUWziuBbVrujfhdRjMI.jpg',
            adult: false,
            poster_path: '/nEkMYwctrUH8ueaAcJFZnAEltMX.jpg',
            credit_id: '52fe4288c3a36847f8026411',
          },
          {
            id: 10186,
            character: 'Carol',
            original_title: 'The Rocker',
            overview:
              "Rob \"Fish\" Fishman is the drummer in '80s hair metal band Vesuvius. He's unceremoniously booted as the group signs a big record deal, is out of the music world for 20 years - and then receives a second chance with his nephew's band.",
            vote_count: 256,
            video: false,
            media_type: 'movie',
            poster_path: '/yQfng0iKQVuGDdI5JeoKPINlXuH.jpg',
            backdrop_path: '/wyAJgNSphpSI2NYWg4VIxN2w8i9.jpg',
            popularity: 8.537,
            title: 'The Rocker',
            original_language: 'en',
            genre_ids: [35, 10402],
            vote_average: 5.8,
            adult: false,
            release_date: '2008-08-20',
            credit_id: '52fe433d9251416c75008d5d',
          },
          {
            id: 11153,
            character: 'Cousin Vicki',
            original_title: "National Lampoon's Vacation",
            overview:
              "Clark Griswold is on a quest to take his family on a quest to Walley World theme park for a vacation, but things don't go exactly as planned.",
            vote_count: 638,
            video: false,
            media_type: 'movie',
            release_date: '1983-07-28',
            vote_average: 7.1,
            title: "National Lampoon's Vacation",
            popularity: 13.185,
            original_language: 'en',
            genre_ids: [35, 12, 10749],
            backdrop_path: '/zcJxJVhvxNHJJ2J7Q7NhgO9nPUV.jpg',
            adult: false,
            poster_path: '/ySI88wO1IFyKGWpSKRTSPilE3t2.jpg',
            credit_id: '52fe44039251416c75025f4f',
          },
          {
            id: 7484,
            character: 'Giselle (voice)',
            original_title: 'Open Season',
            overview:
              'Boog, a domesticated 900lb. Grizzly bear finds himself stranded in the woods 3 days before Open Season. Forced to rely on Elliot, a fast-talking mule deer, the two form an unlikely friendship and must quickly rally other forest animals if they are to form a rag-tag army against the hunters.',
            vote_count: 1263,
            video: false,
            media_type: 'movie',
            release_date: '2006-09-29',
            vote_average: 6.1,
            title: 'Open Season',
            popularity: 11.792,
            original_language: 'en',
            genre_ids: [12, 35, 16],
            backdrop_path: '/7bmzhqOJ9TGXUU5d4pqYUWl3YZ8.jpg',
            adult: false,
            poster_path: '/9TY3wQPNhZ60Mng0JetKEOfXqxU.jpg',
            credit_id: '52fe447fc3a36847f8099bd3',
          },
          {
            id: 24418,
            character: 'Corma Limbs',
            original_title: "Cirque du Freak: The Vampire's Assistant",
            overview:
              'Darren Shan is a regular teenage kid. He and his friend Steve find out about a Freak Show coming to town and work hard at trying to find tickets. They do, and together they go to "Cirque du Freak" where they see many strange acts including a wolf-man and a bearded lady',
            vote_count: 531,
            video: false,
            media_type: 'movie',
            release_date: '2009-10-23',
            vote_average: 5.6,
            title: "Cirque du Freak: The Vampire's Assistant",
            popularity: 15.536,
            original_language: 'en',
            genre_ids: [12, 14, 28, 53],
            backdrop_path: '/fa8wNFBYP3ouGXs3dJDYzMEvj9g.jpg',
            adult: false,
            poster_path: '/nzx9HQOJ1CYgHcITgBXatN0FFxc.jpg',
            credit_id: '52fe4494c3a368484e02aee3',
          },
          {
            id: 8359,
            character: 'Nurse',
            original_title: 'Kit Kittredge: An American Girl',
            overview:
              "The Great Depression hits home for nine year old Kit Kittredge when her dad loses his business and leaves to find work. Oscar nominee Abigail Breslin stars as Kit, leading a splendid cast in the first ever \"American Girl\" theatrical movie. In order to keep their home, Kit and her mother must take in boarders - paying house - guests who turn out to be full of fascinating stories. When mother's lockbox containing all their money is stolen, Kit's new hobo friend Will is the prime suspect. Kit refuses to believe that Will would steal, and her efforts to sniff out the real story get her and friends into big trouble. The police say the robbery was an inside job, committed by someone they know. So if it wasn't Will, then who did it.",
            vote_count: 61,
            video: false,
            media_type: 'movie',
            release_date: '2008-07-02',
            vote_average: 6.3,
            title: 'Kit Kittredge: An American Girl',
            popularity: 9.789,
            original_language: 'en',
            genre_ids: [35, 18, 10751],
            backdrop_path: '/9IXGkjEW7o2aqXfSABfUb4W1Dr9.jpg',
            adult: false,
            poster_path: '/xvOVJmoLlbHFxHw1PBMK72D4jY0.jpg',
            credit_id: '52fe44a2c3a36847f80a159d',
          },
          {
            id: 8849,
            character: 'Dorie',
            original_title: 'Alfie',
            overview:
              'In Manhattan, the British limousine driver Alfie is surrounded by beautiful women, having one night stands with all of them and without any sort of commitment. His best friends are his colleague Marlon and his girl-friend Lonette. Alfie has a brief affair with Lonette, and the consequences of his act forces Alfie to reflect over his lifestyle.',
            vote_count: 424,
            video: false,
            media_type: 'movie',
            poster_path: '/4XjpmslsnWDA5NIyauQvRrarix2.jpg',
            backdrop_path: '/gXDOdcEPi2FxCOTA1hwZTmF0Hv7.jpg',
            popularity: 8.767,
            title: 'Alfie',
            original_language: 'en',
            genre_ids: [35],
            vote_average: 5.6,
            adult: false,
            release_date: '2004-11-05',
            credit_id: '52fe44c0c3a36847f80a8003',
          },
        ],
        crew: [],
        id: 13636,
      },
    },
  },
];
