// flow-typed signature: 34be5b45a506b6ac44faceef211a3f08
// flow-typed version: <<STUB>>/react-circular-progressbar_v1.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-circular-progressbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-circular-progressbar' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-circular-progressbar/dist/index' {
    declare module.exports: any;
}

// Filename aliases
declare module 'react-circular-progressbar/dist/index.js' {
    declare module.exports: $Exports<'react-circular-progressbar/dist/index'>;
}

declare module 'react-circular-progressbar/dist/styles.css' {
    declare module.exports: $Exports<'react-circular-progressbar/dist/styles.css'>;
}
