// flow-typed signature: 1d84b6e70fd8ef35f0caf25090ceee66
// flow-typed version: <<STUB>>/style-it_v2.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-it'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-it' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'style-it/__tests__/Style-01' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-02' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-03' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-04' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-05' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-06' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-07' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-08' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-09' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-10' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-11' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-12' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-13' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-14' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-15' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-16' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-17' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-18' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-19' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-20' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-21' {
  declare module.exports: any;
}

declare module 'style-it/__tests__/Style-22' {
  declare module.exports: any;
}

declare module 'style-it/dist/style-it-standalone' {
  declare module.exports: any;
}

declare module 'style-it/dist/style-it-standalone.min' {
  declare module.exports: any;
}

declare module 'style-it/dist/style-it' {
  declare module.exports: any;
}

declare module 'style-it/dist/style-it.min' {
  declare module.exports: any;
}

declare module 'style-it/lib/index' {
  declare module.exports: any;
}

declare module 'style-it/src/index' {
  declare module.exports: any;
}

declare module 'style-it/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'style-it/__tests__/Style-01.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-01'>;
}
declare module 'style-it/__tests__/Style-02.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-02'>;
}
declare module 'style-it/__tests__/Style-03.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-03'>;
}
declare module 'style-it/__tests__/Style-04.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-04'>;
}
declare module 'style-it/__tests__/Style-05.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-05'>;
}
declare module 'style-it/__tests__/Style-06.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-06'>;
}
declare module 'style-it/__tests__/Style-07.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-07'>;
}
declare module 'style-it/__tests__/Style-08.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-08'>;
}
declare module 'style-it/__tests__/Style-09.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-09'>;
}
declare module 'style-it/__tests__/Style-10.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-10'>;
}
declare module 'style-it/__tests__/Style-11.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-11'>;
}
declare module 'style-it/__tests__/Style-12.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-12'>;
}
declare module 'style-it/__tests__/Style-13.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-13'>;
}
declare module 'style-it/__tests__/Style-14.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-14'>;
}
declare module 'style-it/__tests__/Style-15.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-15'>;
}
declare module 'style-it/__tests__/Style-16.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-16'>;
}
declare module 'style-it/__tests__/Style-17.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-17'>;
}
declare module 'style-it/__tests__/Style-18.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-18'>;
}
declare module 'style-it/__tests__/Style-19.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-19'>;
}
declare module 'style-it/__tests__/Style-20.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-20'>;
}
declare module 'style-it/__tests__/Style-21.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-21'>;
}
declare module 'style-it/__tests__/Style-22.js' {
  declare module.exports: $Exports<'style-it/__tests__/Style-22'>;
}
declare module 'style-it/dist/style-it-standalone.js' {
  declare module.exports: $Exports<'style-it/dist/style-it-standalone'>;
}
declare module 'style-it/dist/style-it-standalone.min.js' {
  declare module.exports: $Exports<'style-it/dist/style-it-standalone.min'>;
}
declare module 'style-it/dist/style-it.js' {
  declare module.exports: $Exports<'style-it/dist/style-it'>;
}
declare module 'style-it/dist/style-it.min.js' {
  declare module.exports: $Exports<'style-it/dist/style-it.min'>;
}
declare module 'style-it/lib/index.js' {
  declare module.exports: $Exports<'style-it/lib/index'>;
}
declare module 'style-it/src/index.js' {
  declare module.exports: $Exports<'style-it/src/index'>;
}
declare module 'style-it/webpack.config.js' {
  declare module.exports: $Exports<'style-it/webpack.config'>;
}
