import SearchResultDropDownLine from '../SearchResultDropDownLine';
import SearchField from '../SearchField';
export default [
  {
    component: SearchResultDropDownLine,
    name: 'movie',
    props: {
      result: {
        vote_average: 6.4,
        vote_count: 1537,
        id: 7555,
        video: false,
        media_type: 'movie',
        title: 'Rambo',
        popularity: 14.285,
        poster_path: '/ec1m7YgBYb4os06OSNW3QBaNYqZ.jpg',
        original_language: 'en',
        original_title: 'Rambo',
        genre_ids: [28, 53],
        backdrop_path: '/mgSMefETH89UnNWMffevxZPKDnO.jpg',
        adult: false,
        overview:
          "When governments fail to act on behalf of captive missionaries, ex-Green Beret John James Rambo sets aside his peaceful existence along the Salween River in a war-torn region of Thailand to take action.  Although he's still haunted by violent memories of his time as a U.S. soldier during the Vietnam War, Rambo can hardly turn his back on the aid workers who so desperately need his help.",
        release_date: '2008-01-24',
      },
    },
  },
  {
    component: SearchResultDropDownLine,
    name: 'person',
    props: {
      result: {
        popularity: 0.6,
        media_type: 'person',
        id: 140833,
        profile_path: '/3v7wsqiFLUxbvCd3wS9QXR3BrAf.jpg',
        name: 'Dack Rambo',
        known_for: [
          {
            original_name: 'Murder, She Wrote',
            id: 484,
            media_type: 'tv',
            name: 'Murder, She Wrote',
            vote_count: 70,
            vote_average: 7.01,
            poster_path: '/j6DC2Xe0SZS6xKS2d6LWL1EGwzX.jpg',
            first_air_date: '1984-09-30',
            popularity: 13.604,
            genre_ids: [9648, 80, 18],
            original_language: 'en',
            backdrop_path: '/5M8bF0BwBk6RtJVrvpS9zj2bcxM.jpg',
            overview:
              'An unassuming mystery writer turned sleuth uses her professional insight to help solve real-life homicide cases.',
            origin_country: ['US'],
          },
          {
            original_name: "Charlie's Angels",
            id: 3382,
            media_type: 'tv',
            name: "Charlie's Angels",
            vote_count: 55,
            vote_average: 6.17,
            poster_path: '/fxIo4qK5nv7G3ymK8xVnOSMklQa.jpg',
            first_air_date: '1976-09-22',
            popularity: 13.205,
            genre_ids: [10759],
            original_language: 'en',
            backdrop_path: '/9G5eEKGznrVG5FaxT4neG0CbgRx.jpg',
            overview:
              'Charlie\'s Angels is an American crime drama television series that aired on ABC from September 1976 to June 1981, producing five seasons and 110 episodes. The series was created by Ivan Goff and Ben Roberts and was produced by Aaron Spelling.\n\nIt plotted the adventures of three females working in a private detective agency in Los Angeles, California, and initially starred Kate Jackson, Farrah Fawcett-Majors, and Jaclyn Smith in the leading roles. David Doyle co-starred as a sidekick to the three women and John Forsythe played the voice of their boss. Later additions to the cast included Cheryl Ladd, who entered the series in season two, Shelley Hack, in season four, and Tanya Roberts, in season five.\n\nDespite mixed reviews from critics and a reputation for merely being "Jiggle TV," the show enjoyed an astonishing popularity with audiences, and was a top ten hit for its first few seasons. Because later cast changes were not well-received and the public\'s taste changed, the show concluded a five-year run in the spring of 1981. The series continues to have a cult and pop culture following through syndication, DVD releases, and subsequent film remakes.',
            origin_country: ['US'],
          },
          {
            original_name: 'Dallas',
            id: 40,
            media_type: 'tv',
            name: 'Dallas',
            vote_count: 48,
            vote_average: 6.25,
            poster_path: '/juEKfVnQEOYUi7CHNlTdfUEe4Eb.jpg',
            first_air_date: '1978-04-02',
            popularity: 15.394,
            genre_ids: [10766, 18],
            original_language: 'en',
            backdrop_path: '/yVCpJou76x0AvHWPBJ7GaioATaj.jpg',
            overview:
              'The world\'s first mega-soap, and one of the most popular ever produced, Dallas had it all. Beautiful women, expensive cars, and men playing Monopoly with real buildings. Famous for one of the best cliffhangers in TV history, as the world asked "Who shot J.R.?" A slow-burner to begin with, Dallas hit its stride in the 2nd season, with long storylines and expert character development. Dallas ruled the airwaves in the 1980\'s.',
            origin_country: ['US'],
          },
        ],
        adult: false,
      },
    },
  },
  {
    component: SearchResultDropDownLine,
    name: 'tv',
    props: {
      result: {
        original_name: 'Modern Family',
        id: 1421,
        media_type: 'tv',
        name: 'Modern Family',
        vote_count: 744,
        vote_average: 7.29,
        poster_path: '/gLAcu4VPCAb90oJvJ4nUJc5ZBQi.jpg',
        first_air_date: '2009-09-23',
        popularity: 46.708,
        genre_ids: [35],
        original_language: 'en',
        backdrop_path: '/snxFgPvHMcpW5f8Q3wu6uRRycww.jpg',
        overview:
          'The Pritchett-Dunphy-Tucker clan is a wonderfully large and blended family. They give us an honest and often hilarious look into the sometimes warm, sometimes twisted, embrace of the modern family.',
        origin_country: ['US'],
      },
    },
  },
  {
    component: SearchField,
    name: 'empty',
    props: {},
  },
];
